esphome:
  name: sonoff-m5-2c
  friendly_name: Sonoff M5 2 Gang
  name_add_mac_suffix: True
  project:
    name: Housemate.Sonoff-M5-2C
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dashboard_import:
  package_import_url: github://housematemy/device-configs/sonoff-m5-2c.yaml@main
  import_full_config: false # or true

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "01175257535"

captive_portal:

web_server:
  port: 80

sensor:  
  - platform: wifi_signal
    name: "RSSI"
    id: sensor_rssi
    update_interval: 90s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    id: sensor_uptime
    update_interval: 300s
    entity_category: "diagnostic"

button:
  - platform: restart
    name: "Restart"
    id: button_restart

switch:
  - platform: gpio
    name: "Left"
    pin: GPIO23
    id: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Right"
    pin: GPIO19
    id: relay_2
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - output.turn_on: led_2
    on_turn_off:
      - output.turn_off: led_2

output:
  - platform: gpio
    id: led_2
    pin:
      number: GPIO22
      inverted: False

  - platform: ledc
    id: pwm_output
    pin: GPIO18
    frequency: 1000 Hz

binary_sensor:
  - platform: gpio
    name: "Left"
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: False
    on_press:
      - switch.toggle: relay_1

  - platform: gpio
    name: "Right"
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: False
    on_press:
      - switch.toggle: relay_2

  - platform: gpio
    id: "fixgpio"
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true 

light:
  - platform: status_led
    name: "Connection LED"
    id: led_status
    pin:
      number: GPIO05
      inverted: True
    restore_mode: ALWAYS_OFF
    entity_category: 'config'

  - platform: monochromatic
    output: pwm_output
    name: "LEDs"
    restore_mode: RESTORE_DEFAULT_OFF
    icon: 'mdi:led-outline'
    entity_category: 'config'